#!/usr/bin/env python3

from setuptools import find_packages, setup

setup(
    name='gpugt',
    version='0.0.0.dev0',
    description=(
        'An open-source Python implementation of GPU-accelerated'
        ' counterfactual regret minimization'
    ),
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/uoftcprg/gpugt',
    author='Universal, Open, Free, and Transparent Computer Poker Research Group',
    author_email='juhok@andrew.cmu.edu',
    license='MIT',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'Intended Audience :: Education',
        'Topic :: Education',
        'Topic :: Games/Entertainment',
        'Topic :: Games/Entertainment :: Board Games',
        'Topic :: Scientific/Engineering',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3 :: Only',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
    ],
    keywords=[
        'artificial-intelligence',
        'deep-learning',
        'game',
        'game-development',
        'game-theory',
        'holdem-poker',
        'imperfect-information-game',
        'libratus',
        'pluribus',
        'poker',
        'poker-engine',
        'poker-evaluator',
        'poker-game',
        'poker-hands',
        'poker-library',
        'poker-strategies',
        'python',
        'reinforcement-learning',
        'texas-holdem',
    ],
    project_urls={
        'Documentation': 'https://gpugt.readthedocs.io/en/latest/',
        'Source': 'https://github.com/uoftcprg/gpugt',
        'Tracker': 'https://github.com/uoftcprg/gpugt/issues',
    },
    packages=find_packages(),
    install_requires=[
        'cupy-cuda13x>=13.6.0,<14',
        'noregret~=0.0.0.dev2',
        'numpy>=2.0,<3',
        'scipy>=1.14.0,<2',
    ],
    python_requires='>=3.11',
)
